map_while_grounded: true

mapping:

  # resolution on the lowest level (fractor = 0, depth = max depth)
  resolution: 0.4 # [m]

  # fractor = how many levels from the lowest level (the higherst res)
  #           should we work on
  # current_resolution = resolution * 2 ^ fractor
  initial_fractor: 0

global_map:

  # the publisher rate of the full map
  rate: 1.0 # [Hz]

  # should we prune the map before publishing?
  compress: true

  publish_full: true # should publish map with full probabilities?
  publish_binary: false # should publish map with binary occupancy?

local_map:

  # should create a local map from the global map?
  enabled: true

  # the bounding box distance of the local map
  horizontal_distance: 10.0
  vertical_distance: 10.0

  # the publisher rate of the local map
  rate: 3.0 # [Hz]

  max_computation_duty_cycle: 0.33

  publish_full: true # should publish map with full probabilities?
  publish_binary: false # should publish map with binary occupancy?

unknown_rays:

  update_free_space: true
  clear_occupied: false # beware, setting this to true is very dangerous
  ray_distance: 15.0

# for point cloud raycasting
sensor_params:

  3d_lidar:

    n_sensors: 0

    # sensor_0:

    #   max_range: 20.0 # [m]

    #   vertical_fov_angle: deg(90.0)
    #   vertical_rays: 64
    #   horizontal_rays: 64

  depth_camera:

    n_sensors: 0

    # sensor_0:

    #   max_range: 9.0 # [m]

    #   horizontal_fov_angle: deg(70.0)
    #   vertical_fov_angle: deg(35.0)
    #   horizontal_rays: 80
    #   vertical_rays: 45

  2d_lidar:

    n_sensors: 0

    # sensor_0:

    #   max_range: 10.0 # [m]

    #   horizontal_rays: 40

sensor_model:

  hit: 0.95  # [0, 1]
  miss: 0.45 # [0, 1]
  min: 0.3  # [0, 1]
  max: 0.7  # [0, 1]
